### ISSUE TITLE
Remove formatting button gone when FreeHelp Active

### ISSUE THREAD

**Issue by andrewlimaza** [zackkatz/FreeHelp#4]
Hi there,

One of our support engineers noticed that the "Clear Formatting" button from the toolbar is missing once FreeHelp is activated.

**Screenshots**

Before
![Screenshot 2023-07-31 at 17 03 05](https://github.com/zackkatz/FreeHelp/assets/12629136/594af9db-99ec-47ff-9c39-4322307dd99d)

After
![Screenshot 2023-07-31 at 17 03 29](https://github.com/zackkatz/FreeHelp/assets/12629136/3d6a9d21-a707-4e5f-a8ee-9f7cef5d8b27)

**Comment by andrewlimaza** [comment]
I've looked at the code and see this is intentional. It would be nice to keep just this (or make it filterable on what buttons you can show/hide). Our team requests the "Remove Formatting" button. It's easy enough to put back, but just thought to share this feedback Zack.

Thanks again for this! :)

**Comment by zackkatz** [comment]
Hi @andrewlimaza, thanks for suggesting. I removed the code.

**Comment by andrewlimaza** [comment]
Thanks @zackkatz - I wasn't expecting it to be removed but it helps us.

Happy to help wherever possible 👍
